name: FreeBSD build

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 6'  # Every Saturday at 4am

jobs:
  build:
    name: build (Qt ${{ matrix.qt }})

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - qt: 5
          - qt: 6

    env:
      QTVER: ${{ matrix.qt }}

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: FreeBSD build
      uses: vmactions/freebsd-vm@v1
      with:
        envs: QTVER
        usesh: true
        prepare: |
          if [ "${QTVER}" == 5 ]; then
            pkg install -y git gmake libX11 qt5-core qt5-gui qt5-widgets qt5-buildtools pkgconf
          else
            pkg install -y git gmake libX11 qt6 pkgconf
          fi
          git clone --depth 1 https://github.com/FreeSpacenav/libspnav
          cd libspnav
          ./configure
          gmake
          gmake install

        run: |
          ./configure --qt${QTVER}
          gmake
          gmake DESTDIR=spnavcfg-freebsd install

    - uses: actions/upload-artifact@v4
      with:
        name: spnavcfg-freebsd-qt${{ matrix.qt }}
        path: spnavcfg-freebsd

# vi:ts=2 sts=2 sw=2 expandtab:
