name: FreeBSD build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: FreeBSD build
      uses: vmactions/freebsd-vm@v1
      with:
        prepare: |
          pkg install -y git gmake libX11 qt5-core qt5-gui qt5-widgets qt5-buildtools pkgconf
          git clone https://github.com/FreeSpacenav/libspnav
          cd libspnav
          ./configure
          gmake
          gmake install

        run: |
          ./configure
          gmake UIC=uic-qt5 MOC=moc-qt5 RCC=rcc-qt5
          gmake DESTDIR=spnavcfg-freebsd install

    - uses: actions/upload-artifact@v4
      with:
        name: spnavcfg-freebsd
        path: spnavcfg-freebsd

# vi:ts=2 sts=2 sw=2 expandtab:
