name: MacOS X build

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 6'  # Every Saturday at 4am

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: install dependencies
      run: |
        brew install xquartz libx11 qt@5 pkg-config
        brew link qt@5 --force
        git clone --depth 1 https://github.com/FreeSpacenav/libspnav
        cd libspnav
        ./configure
        make
        sudo make install

    - name: configure
      run: CFLAGS=-I/usr/X11R6/include LDFLAGS=-L/usr/X11R6/lib ./configure

    - name: build
      run: make

    - name: stage install
      run: DESTDIR=spnavcfg-macosx make install

    - uses: actions/upload-artifact@v4
      with:
        name: spnavcfg-macosx
        path: spnavcfg-macosx

# vi:ts=2 sts=2 sw=2 expandtab:
