name: GNU/Linux build

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 6'  # Every Saturday at 4am

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install qtbase5-dev
        git clone https://github.com/FreeSpacenav/libspnav
        cd libspnav
        ./configure
        make
        sudo make install

    - name: configure
      run: ./configure

    - name: build
      run: make

    - name: stage install
      run: DESTDIR=spnavcfg-gnulinux make install

    - uses: actions/upload-artifact@v4
      with:
        name: spnavcfg-gnulinux
        path: spnavcfg-gnulinux

# vi:ts=2 sts=2 sw=2 expandtab:
